BATCH_SIZE = 16 
LR = 0.0001 #[0.001, 0.00001]
NUM_CLASSES = 1
PATCH_SIZE = 4
WIN = 8 
HEADS = 8
SWIN_DEPTH = 2 #4
EMBED_DIM  = 96 
EPOCHS = 50 
PATIENCE = 7
LOSS_FUNCTION = 'BOTH' #'BCE', 'DICE'
IMAGE_SIZE = 256
OPTIMIZER = 'ADAMW' #['ADAM','SGD_M'] 
DROPOUT = 0.2 #[0.0, 0.1]
IN_CHANNELS = 1
USE_ATTENTION = 'TRUE' #'FALSE' #whether to use attention gates in skip connections or not


